---
roles:
  - name: rcrawf.zram
    src: https://github.com/rcrawf/ansible-role-zram
  - name: diademiemi.flatpak
  - name: egdoc.rpmfusion

collections:
  - name: community.general
  - name: ansible.posix
