services:
  qwen-unsloth-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    container_name: qwen3.6-unsloth-moe
    ports:
      - "8080:8080"
    volumes:
      - hf:/root/.cache/huggingface
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      -hf unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q4_K_XL
      -ngl 99
      -cmoe
      -c 131072
      -fa on
      -t 8
      -tb 8
      -b 1024
      -ub 1024
      --image-min-tokens 1024
      --image-max-tokens 1024
      --temp 0.6
      --top-p 0.95
      --top-k 20
      --min-p 0.00
      --chat-template-kwargs '{"preserve_thinking":true}'

volumes:
  hf:
