# Created using winget configure export 1.28.220
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.3
$schema: https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json
metadata:
  winget:
    processor:
      identifier: "dscv3"
resources:
- name: winget_Docker.DockerDesktop
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Docker.DockerDesktop"
  properties:
    id: "Docker.DockerDesktop"
    source: "winget"
- name: winget_Git.Git
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Git.Git"
  properties:
    id: "Git.Git"
    source: "winget"
- name: winget_Hasleo.BackupSuiteFree
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Hasleo.BackupSuiteFree"
  properties:
    id: "Hasleo.BackupSuiteFree"
    source: "winget"
- name: winget_ONLYOFFICE.DesktopEditors
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C ONLYOFFICE.DesktopEditors"
  properties:
    id: "ONLYOFFICE.DesktopEditors"
    source: "winget"
- name: winget_Microsoft.PowerShell
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Microsoft.PowerShell"
  properties:
    id: "Microsoft.PowerShell"
    source: "winget"
- name: winget_WinDirStat.WinDirStat
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C WinDirStat.WinDirStat"
  properties:
    id: "WinDirStat.WinDirStat"
    source: "winget"
- name: winget_Yandex.Music
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Yandex.Music"
  properties:
    id: "Yandex.Music"
    source: "winget"
- name: winget_WinMerge.WinMerge
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C WinMerge.WinMerge"
  properties:
    id: "WinMerge.WinMerge"
    source: "winget"
- name: winget_ElementLabs.LMStudio
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C ElementLabs.LMStudio"
  properties:
    id: "ElementLabs.LMStudio"
    source: "winget"
- name: winget_Microsoft.VisualStudioCode
  type: Microsoft.WinGet/Package
  metadata:
    description: "\u0423\u0441\u0442\u0430\u043D\u043E\u0432\u0438\u0442\u044C Microsoft.VisualStudioCode"
  properties:
    id: "Microsoft.VisualStudioCode"
    source: "winget"
