---
- name: Configure zRAM
  hosts: all
  become: true
  vars:
    zram_compression: zstd
    zram_percentage: 100 # 100% of RAM
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name: [zram-tools]
        state: present
        update_cache: true
    - name: Create optimized zRAM configuration
      ansible.builtin.copy:
        dest: /etc/default/zramswap
        mode: "0644"
        content: |
          # Ansible managed
          ALGO={{ zram_compression }}
          PERCENT={{ zram_percentage }}
          PRIORITY=100
    - name: Enable and restart zramswap service
      ansible.builtin.systemd:
        name: zramswap
        state: restarted
        enabled: true
        daemon_reload: true
